diagonalworks/diagonal-b6

Makefile, proto/compact.proto, src/diagonal.works/b6/ingest/compact/build.go, src/diagonal.works/b6/ingest/compact/encoding.go, src/diagonal.works/b6/ingest/compact/encoding_test.go, src/diagonal.works/b6/ingest/compact/world.go
Use semver versions for the compact index, to match the approach for the API, and to track changes that don't break backward compatability. Use a protobuf to encode the header data, to allow flexibility where memory isn't at a premium.
Invalidates all previous indices by changing the header magic.
=> Use semver versions for the compact index.

src/diagonal.works/b6/api/functions/functions.go, src/diagonal.works/b6/api/functions/search.go, src/diagonal.works/b6/api/functions/sightline.go, src/diagonal.works/b6/api/vm.go, src/diagonal.works/b6/cmd/b6-ingest-gb-uprn/b6-ingest-gb-uprn.go, src/diagonal.works/b6/ingest/compact/world_test.go, src/diagonal.works/b6/ingest/features.go, src/diagonal.works/b6/ingest/gb/uprn/source.go, src/diagonal.works/b6/ingest/mutable_test.go, src/diagonal.works/b6/ingest/overlay_test.go, src/diagonal.works/b6/ingest/source.go, src/diagonal.works/b6/ingest/source_test.go, src/diagonal.works/b6/ingest/spatial_test.go, src/diagonal.works/b6/ingest/testing.go, src/diagonal.works/b6/spatial.go
Reworks IntersectsCap{} to cache the polygon used to approximate the cap, and parallises the output of uprn ingest while avoiding dynamic allocation of points.
=> Speed up UPRN ingest by parallelising emit, and improving filtering.

Makefile, README.md, etc/cloudbuild.nightly.yaml, src/diagonal.works/b6/ingest/compact/encoding.go
Add a nightly build that pushes a new docker image, including fixing the documentation. Remove 'docker' from the all Makefile target, since we don't copy the docker configuration into the image during build. In passing, remove unnecessary logging from the index build.
=> Add a nightly build that pushes a new docker image.

etc/b6build-nightly-notifier.yaml, etc/b6build-nightly-template.json, src/diagonal.works/b6/api/functions/export.go, src/diagonal.works/b6/cmd/b6-connect/b6-connect.go, src/diagonal.works/b6/cmd/b6-ingest-gb-codepoint/b6-ingest-gb-codepoint.go, src/diagonal.works/b6/cmd/b6-ingest-gb-uprn/b6-ingest-gb-uprn.go, src/diagonal.works/b6/cmd/b6-ingest-gdal/b6-ingest-gdal.go, src/diagonal.works/b6/cmd/b6-ingest-osm/b6-ingest-osm.go, src/diagonal.works/b6/cmd/b6-ingest-terrain/b6-ingest-terrain.go, src/diagonal.works/b6/graph/connectivity.go, src/diagonal.works/b6/ingest/basic.go, src/diagonal.works/b6/ingest/compact/build.go, src/diagonal.works/b6/ingest/compact/overlay_test.go, src/diagonal.works/b6/ingest/compact/world.go, src/diagonal.works/b6/ingest/compact/world_test.go, src/diagonal.works/b6/ingest/features.go, src/diagonal.works/b6/ingest/gb/uprn/source.go, src/diagonal.works/b6/ingest/gdal/source.go, src/diagonal.works/b6/ingest/mutable.go, src/diagonal.works/b6/ingest/osm.go, src/diagonal.works/b6/ingest/testing.go, src/diagonal.works/b6/ingest/world_test.go, src/diagonal.works/b6/world.go
Parallelise ingest of multiple gdal files. Rename the Cores option to Goroutines to clarify the semantics, as the code increasingly relies the semantics of numbered goroutines emitting one feature at a time. In passing, add build notifier configuration.
=> Parallelise ingest of multiple gdal files.

src/diagonal.works/b6/encoding/uint64map.go, src/diagonal.works/b6/go.mod, src/diagonal.works/b6/go.sum, src/diagonal.works/b6/ingest/compact/read.go, src/diagonal.works/b6/ingest/compact/world.go
Use mmap to allocate memory for worlds read from cloud storage, to bypass the go garbage collector. Also parallelise reads.
=> Use mmap to allocate memory for worlds read from cloud storage.

python/diagonal_b6/b6_test.py, python/diagonal_b6/features.py, src/diagonal.works/b6/api/functions/sightline.go
Fix a sightline panic that occured when an edge ended exactly on the reference line between the point and the North pole. As it was part of the same bug report, also allow features to be passed back to the b6 server by encoding them as a call to find-feature with their ID. In passing, correct a bug that prevented str() from working on features given we now use string namespaces, not integers.
gh-42: str() on features, and sending features to the backend
gh-43: sightline crash
=> Fix a sightline panic, and allow features to be passed back in Python.

src/diagonal.works/b6/api/shell.go, src/diagonal.works/b6/api/shell_test.go, src/diagonal.works/b6/cmd/b6-ingest-gdal/b6-ingest-gdal.go, src/diagonal.works/b6/cmd/b6/js/b6.js, src/diagonal.works/b6/ids.go, src/diagonal.works/b6/ids_test.go, src/diagonal.works/b6/ingest/compact/build.go, src/diagonal.works/b6/ingest/gdal/source.go, src/diagonal.works/b6/ingest/gdal/source_test.go, src/diagonal.works/b6/ui/blocks.go
Make it possible to import 2022 census boundaries by increasing the buffer size for encoding features, and adding a command line flag to use the 2022 ID namespace. In passing, make tab copy a suggestion with sending it in the b6 UX.
=> Make it possible to import 2022 census boundaries.

src/diagonal.works/b6/cmd/b6-ingest-gdal/b6-ingest-gdal.go, src/diagonal.works/b6/cmd/b6/js/b6.js, src/diagonal.works/b6/cmd/b6/js/static/b6.css, src/diagonal.works/b6/graph/connectivity.go, src/diagonal.works/b6/ingest/compact/encoding.go, src/diagonal.works/b6/ingest/compact/encoding_test.go, src/diagonal.works/b6/ingest/compact/world.go, src/diagonal.works/b6/ingest/features.go, src/diagonal.works/b6/ingest/features_test.go, src/diagonal.works/b6/ingest/gdal/inputs.go, src/diagonal.works/b6/ingest/gdal/source.go, src/diagonal.works/b6/ingest/mutable.go, src/diagonal.works/b6/ingest/mutable_test.go, src/diagonal.works/b6/ingest/source.go, src/diagonal.works/b6/ui/blocks.go, src/diagonal.works/b6/world.go
As some GDAL transform operations are slow, we previosuly read entire shapefiles into RAM before transforming them. This is impractical for large shapefiles, so we now transform features in batches.
Also correct some issues that surfaced while importing OS open data, for example, tag propagation on modified features.
=> Batch transformations to support the ingestion of large shapefiles.

python/diagonal_b6/b6_test.py, src/diagonal.works/b6/api/collections.go, src/diagonal.works/b6/api/functions/change.go, src/diagonal.works/b6/api/functions/functions.go, src/diagonal.works/b6/api/functions/geojson.go, src/diagonal.works/b6/api/functions/geojson_test.go, src/diagonal.works/b6/api/protos.go, src/diagonal.works/b6/cmd/b6-api/b6-api.go, src/diagonal.works/b6/cmd/b6-ingest-gb-uprn/b6-ingest-gb-uprn.go, src/diagonal.works/b6/ingest/change.go, src/diagonal.works/b6/ingest/change_test.go, src/diagonal.works/b6/ingest/gb/uprn/source.go, src/diagonal.works/b6/spatial.go, src/diagonal.works/b6/ui/blocks.go
In passing, turn panics into errors when we can't convert a value we're trying to return over GRPC, correct loop inversion when parsing geojson, correct filtering for UPRN import following the Context parameter position switch, and render geojson objects that are plain geometries rather than features.
Fixes #60.
=> Support merging changes, and parsing geojson files.

python/diagonal_b6/b6_test.py, python/diagonal_b6/expression.py, python/diagonal_b6/features.py, python/diagonal_b6/generate_api.py, python/diagonal_b6/geometry.py, python/diagonal_b6/query.py
Support map() with functions that return a literal. Previously, we only supported b6 expressions, eg:
b6.map(buildings, lambda: building: building.area()) as we relied on inferring the type of the collection from the expression. To support literals, we build a map of literal types to the corresponding expression result type in the generated code.
=> Support map() with functions that return a literal.

src/diagonal.works/b6/cmd/b6/js/b6.js, src/diagonal.works/b6/cmd/b6/js/main.js, src/diagonal.works/b6/cmd/b6/js/package.json, src/diagonal.works/b6/cmd/b6/js/rollup.config.js
Wrap the b6 JS in a module, for inclusion in other projects. This change doesn't introduce a sane API, rather just adds the necessary build infrastructure.
=> Wrap the b6 JS in a module, for inclusion in other projects.

src/diagonal.works/b6/search/tree_test.go
I think Advance should return false instead of true, as we're advancing beyond the end of the structure. Also, there was code to handle the case there Advance returns false, but none of the existing tests set 'ok' to 'false'.
=> Fix TestTreeListAdvanceOnDeletedIterator/AdvanceBeyondEnd

src/diagonal.works/b6/cmd/b6-ingest-gdal/b6-ingest-gdal.go, src/diagonal.works/b6/encoding/uint64map.go, src/diagonal.works/b6/ingest/compact/build.go, src/diagonal.works/b6/ingest/compact/overlay_test.go, src/diagonal.works/b6/ingest/compact/world.go, src/diagonal.works/b6/ingest/compact/world_test.go, src/diagonal.works/b6/ingest/gdal/inputs.go, src/diagonal.works/b6/ingest/gdal/source.go
Correctly destroy the resources used by gdal features during ingest, to avoid memory exhaustion when importing large files. In passing, add support for ingesting a named layer, and separate writing features from the search index itself, to allow for garbage collection between the two phases.
=> Destroy gdal features to support ingest of large files.

src/diagonal.works/b6/api/collections.go, src/diagonal.works/b6/expression.go, src/diagonal.works/b6/ingest/change.go, src/diagonal.works/b6/ingest/features.go, src/diagonal.works/b6/ingest/features_test.go, src/diagonal.works/b6/ingest/mutable.go, src/diagonal.works/b6/ingest/osm.go, src/diagonal.works/b6/ingest/tokens.go, src/diagonal.works/b6/ingest/validate.go, src/diagonal.works/b6/ingest/yaml.go, src/diagonal.works/b6/ingest/yaml_test.go, src/diagonal.works/b6/renderer/renderer_test.go, src/diagonal.works/b6/world.go
Support expressions as features within the world. Adds a new, non proto, based representation for expressions, which will become the standard internal representation for, eg, the VM in a future CL. Support exporting expressions as YAML, though not yet in a compact world. Moves Tags from b6/ingest to b6/ for wider reuse.
=> Support expressions as features.

src/diagonal.works/b6/api/functions/graph.go, src/diagonal.works/b6/api/functions/graph_test.go, src/diagonal.works/b6/cmd/b6/js/b6.js, src/diagonal.works/b6/expression.go, src/diagonal.works/b6/ingest/compact/read.go, src/diagonal.works/b6/ingest/yaml.go, src/diagonal.works/b6/ingest/yaml_test.go, src/diagonal.works/b6/ui/lines.go, src/diagonal.works/b6/ui/ui.go
Also return errors when exporting Features as YAML, as we don't actually support that. Handle collection and expression IDs in the JS code, and remove Identifiable from the return type of accessible(), in preparation for not supporting it.
=> Use collections, not relations, for the render context feature.

src/diagonal.works/b6/api/functions/graph.go, src/diagonal.works/b6/graph/graph.go, src/diagonal.works/b6/ui/lines.go, src/diagonal.works/b6/ui/lines_test.go, src/diagonal.works/b6/ui/ui.go, src/diagonal.works/b6/ui/ui_test.go
Add transit weights for `accessible`. Also change the maximum weight supplied to be a time, rather than a constant without units. In passing, show the paths referenced by a point in the UI.
=> Add transit weights for `accessible`.

python/diagonal_b6/connect.py, src/diagonal.works/b6/api/shell.go, src/diagonal.works/b6/api/shell_test.go, src/diagonal.works/b6/cmd/b6/js/b6.js, src/diagonal.works/b6/cmd/b6/js/static/b6.css, src/diagonal.works/b6/expression.go, src/diagonal.works/b6/renderer/renderer.go, src/diagonal.works/b6/ui/labels.go
In passing: render rail tracks on the map, show error messages for failed backend requests, and remove event handlers when reusing rendered elements.
=> Correctly simplify partial and queries.

docker/Dockerfile.b6-build.inc, docker/Dockerfile.b6.inc, src/diagonal.works/b6/go.mod, src/diagonal.works/b6/go.sum
Upgrade the build environment to ubuntu mantic, for GDAL 3.6, which is the only version for which the wrapper works with go 1.21.
=> Upgrade the build environment to ubuntu mantic.

src/diagonal.works/b6/cmd/b6/js/.eslintrc.json, src/diagonal.works/b6/cmd/b6/js/.prettierignore, src/diagonal.works/b6/cmd/b6/js/.prettierrc, src/diagonal.works/b6/cmd/b6/js/Makefile, src/diagonal.works/b6/cmd/b6/js/b6.js, src/diagonal.works/b6/cmd/b6/js/main.js, src/diagonal.works/b6/cmd/b6/js/package.json, src/diagonal.works/b6/cmd/b6/js/rollup.config.js, src/diagonal.works/b6/cmd/b6/js/static/b6.css, src/diagonal.works/b6/cmd/b6/js/static/index.html, src/diagonal.works/b6/cmd/b6/js/static/palette.html
This PR adds [ESlint](https://eslint.org/) for linting and [Prettier](https://prettier.io/) for formatting.
We add explicit prettier configuration so that we don't run into mismatches if we have different workspace formatting preferences in our code editor
=> Add prettier and eslint

src/diagonal.works/b6/cmd/b6/js/static/b6.css
Fix the issue where unnecessary scroll bars were showing on stacks.
How to reproduce on Mac:
Go to System Settings > Appearance > Scroll bar behavior and set "Show scroll bars" to "Always".
Changes `overflow-y: scroll` to `overflow-y: auto` so that scroll bars are only shown when content overflows.
Additionally, because the width of line elements was fixed, it would result in the following "ghost" borders (image below) when some elements in the stack had scrollbars. We remove this, this also avoids a width change when elements become scrollable, avoiding a layout shift.
The first commit 2ca47f1 in the PR includes slight changes due to formatting. Is there somewhere where we define these formatting configs?
=> Fix unnecessary scroll bars

src/diagonal.works/b6/cmd/b6/js/b6.js, src/diagonal.works/b6/cmd/b6/js/static/b6.css
The goal of this PR is to fix the issues identified with the visualization of the buckets. Namely:
In addition to the issues described above, this PR includes some additional experiments around the color encoding used in the bucket visualization:
- 🧪 Experiment 1: Color Scale
In addition to the issues above, there might be an opportunity to test different color scales. Our current color scale is similar to [viridis](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html), where the lowest value (1) is a darker shade of blue/purple, and the highest value (5) is a light yellow. This means that there's little contrast between 0 (white) and 5, and a large contrast between 0 and 1 - this may be unintuitive when reading the map. A classed sequential color scale could be …
=> Bucket interaction and visualization 

src/diagonal.works/b6/api/functions/export.go, src/diagonal.works/b6/cmd/b6-connect/b6-connect.go, src/diagonal.works/b6/cmd/b6-ingest-gb-codepoint/b6-ingest-gb-codepoint.go, src/diagonal.works/b6/cmd/b6-ingest-gb-uprn/b6-ingest-gb-uprn.go, src/diagonal.works/b6/cmd/b6-ingest-gdal/b6-ingest-gdal.go, src/diagonal.works/b6/cmd/b6-ingest-osm/b6-ingest-osm.go, src/diagonal.works/b6/cmd/b6-ingest-terrain/b6-ingest-terrain.go, src/diagonal.works/b6/ingest/compact/build.go, src/diagonal.works/b6/ingest/compact/overlay_test.go, src/diagonal.works/b6/ingest/compact/world_test.go
Writing a compact world requires an IO layer that supports writing at a specific byte position, so writing directly to gcs (or s3) isn't possible. Write to a temporary file local file instead, then copy that to gcs, deleting the local file.
=> Support writing to cloud from b6-ingest-osm and b6-connect.

Makefile, data/tests/.gitignore, python/diagonal_b6/b6_test.py, src/diagonal.works/b6/ingest/compact/world.go
Build and use a compact index of Granary Square for the Python unit tests. Fix the resulting test failures by providing a basic implementation of FindReferences, which should ultimately be replaced when we implement a unified way of storing references in the compact world encoding.
=> Provide a basic implementation of FindReferences for compact worlds.

src/diagonal.works/b6/expression.go, src/diagonal.works/b6/ingest/yaml_test.go, src/diagonal.works/b6/world.go, src/diagonal.works/b6/world_test.go
We currently use tags with string values in configuration files for, eg, the basemap rendering rules. Support the old way of serialising them to YAML (as, eg, #highway=pedestrian), while also supporting the serialisation of more complex tag values via the existing YAML serialisation code for literals in expressions (which are the same thing - so b6.Literal and b6.Value should merge).
=> Support the exist tag serialisation format for tags with string values.

src/diagonal.works/b6/cmd/b6/js/b6.js, src/diagonal.works/b6/ingest/compact/encoding.go, src/diagonal.works/b6/ingest/compact/world.go, src/diagonal.works/b6/merged_test.go, src/diagonal.works/b6/renderer/renderer.go, src/diagonal.works/b6/ui/lines.go, src/diagonal.works/b6/ui/ui.go, src/diagonal.works/b6/world.go
Correct map rendering rules loaded from YAML, since default rules could either be nil, or the empty string. Add a convenience accessor for string values in passing, since b6.String can't easily be compared for equality, since it's an interface.
In passing, swap click/shift click in the UI to match baseline.
=> Correct map rendering rules loaded from YAML

src/diagonal.works/b6/api/shell.go
Support unparsing query expressions, which are pointers rather than instances.
=> Support unparsing query expressions.

src/diagonal.works/b6/ingest/compact/world.go, src/diagonal.works/b6/ingest/compact/world_test.go
FindAreasByPoint should check all feature blocks, as a single namespace can be split across multiple blocks, for example, when OSM data for multiple areas is loaded from separate index files.
=> FindAreasByPoint should check all feature blocks.

src/diagonal.works/b6/ingest/compact/encoding.go
rather than unmarshalling one by one
=> call tags/unmarshal in all tags for consistency

src/diagonal.works/b6/ingest/compact/build.go, src/diagonal.works/b6/ingest/compact/encoding.go, src/diagonal.works/b6/ingest/compact/world_test.go
Check read value and type are not zero when attempting to extract a uint64 from the buffer which happens when a read error occurs, and if so backtrack to reading a uint32
=> Correctly infer value type

src/diagonal.works/b6/ingest/gdal/source.go
Adapt gdal import for generic features - don't replace all the tags, as there are now point and path tags added on feature creation.
=> Adapt gdal import for generic features.

src/diagonal.works/b6/api/api.go, src/diagonal.works/b6/api/collections.go, src/diagonal.works/b6/api/functions/collections.go, src/diagonal.works/b6/api/functions/collections_test.go, src/diagonal.works/b6/api/functions/features.go, src/diagonal.works/b6/api/functions/geojson.go, src/diagonal.works/b6/api/functions/graph.go, src/diagonal.works/b6/api/functions/map.go, src/diagonal.works/b6/api/functions/map_test.go, src/diagonal.works/b6/api/functions/materialise.go, src/diagonal.works/b6/api/functions/search.go, src/diagonal.works/b6/api/functions/vm_test.go, src/diagonal.works/b6/api/vm.go, src/diagonal.works/b6/collections.go, src/diagonal.works/b6/expression.go, src/diagonal.works/b6/ingest/basic.go, src/diagonal.works/b6/world.go
Allow functions to access the Expression that called them, to support persisting expressions for rerunning later.
=> Allow functions to access the Expression that called them.

src/diagonal.works/b6/api/histogram.go, src/diagonal.works/b6/ingest/features.go, src/diagonal.works/b6/renderer/histogram.go, src/diagonal.works/b6/ui/histogram.go, src/diagonal.works/b6/ui/histogram_test.go, src/diagonal.works/b6/world.go
Support rendering histograms directly from accessibility results, by assuming that FeatureID, FeatureID collections represent origin/destinaion pairs, computing the buckets at render-time. This gives us more flexibility in visualisation.
=> Support rendering histograms directly from accessibility results.

frontend/package.json, frontend/src/App.tsx, frontend/src/atoms/app.tsx, frontend/src/atoms/location.ts, frontend/src/components/Comparator.tsx, frontend/src/components/ScenarioMap.tsx, frontend/src/components/ScenarioTab.tsx, frontend/src/components/adapters/AtomAdapter.tsx, frontend/src/components/adapters/ChipAdapter.tsx, frontend/src/components/adapters/ChoiceAdapter.tsx, frontend/src/components/adapters/ConditionalAdapter.tsx, frontend/src/components/adapters/HistogramAdapter.tsx, frontend/src/components/adapters/LabelledIconAdapter.tsx, frontend/src/components/adapters/LineAdapter.tsx, frontend/src/components/adapters/ShellAdapter.tsx, frontend/src/components/adapters/StackAdapter.tsx, frontend/src/components/adapters/SubstackAdapter.tsx, frontend/src/components/system/Histogram.stories.tsx, frontend/src/components/system/Histogram.tsx, frontend/src/index.css, frontend/src/lib/b6.ts, frontend/src/lib/context/app.tsx, frontend/src/lib/context/comparator.tsx, frontend/src/lib/context/line.tsx, frontend/src/lib/context/outliner.tsx, frontend/src/lib/context/scenario.tsx, frontend/src/types/generated/api.ts, frontend/src/types/generated/geometry.ts, frontend/src/types/generated/ui.ts, frontend/src/types/startup.ts
Fetch comparison for an analysis form `/evaluate` endpoint and use the result to display data in the comparison panel.
Additionally, display amenity icons when relevant.
=> Add comparison histograms and show layers

frontend/src/components/ScenarioMap.tsx, frontend/src/components/adapters/StackAdapter.tsx, frontend/src/lib/context/comparator.tsx, frontend/src/lib/context/scenario.tsx
Make it visible when a building in a histogram bucket is also highlighted. 
Fixes the issue with the comparison histograms not allowing selection.
=> feat: highlight and select improvements on comparison histogram

frontend/src/App.tsx, frontend/src/atoms/app.tsx, frontend/src/components/ScenarioMap.tsx, frontend/src/components/ScenarioTab.tsx, frontend/src/components/adapters/StackAdapter.tsx, frontend/src/lib/context/app.tsx, frontend/src/lib/context/comparator.tsx, frontend/src/lib/context/outliner.tsx, frontend/src/lib/context/scenario.tsx
Fix a few interaction issues related to the multi-tab behavior, namely:
Previously, this would cause an overlap of histograms which led to an incorrect state. We now prioritize an active query layer, and only if none exists, show the comparison layers.
=> fix interaction issues related with multi tabs

frontend/src/components/Comparator.tsx, frontend/src/components/ScenarioMap.tsx, frontend/src/components/ScenarioTab.tsx, frontend/src/components/adapters/LineAdapter.tsx, frontend/src/components/adapters/ShellAdapter.tsx, frontend/src/components/adapters/StackAdapter.tsx, frontend/src/components/adapters/SubstackAdapter.tsx, frontend/src/components/system/Line.stories.tsx, frontend/src/components/system/Line.tsx, frontend/src/components/system/Stack.tsx, frontend/src/lib/context/app.tsx, frontend/src/lib/context/comparator.tsx, frontend/src/lib/context/outliner.tsx, frontend/src/lib/context/scenario.tsx
The goal is to add a visibility toggle to outlines. This toggle allows users to turn the respective outliner's map layers/markers on or off.
When there are multiple outlines in the view, each with a corresponding histogram or other geographical layers, we need a way to control what is displayed on the map. For example, displaying all the histograms at once could lead to overlap issues.
Previously, visibility was determined by whether an outlier was active, which overlapped with the drag behavior. So, we are adding a new "show" property to manage visibility, which the user can control via the toggle.
https://github.com/diagonalworks/diagonal-b6/assets/23224854/94b1c5a5-c278-4d82-b290-2f83adfa01d5
=> Add visibility toggle on outliners

frontend/src/hooks/usePersistURL.ts
This PR removes the encoding of the URL search parameters.
We choose to no longer encode the URL params for two reasons:
- We want to keep the URL human-readable and editable
- On the production environment, we noticed flaky behavior of URL encoding/decoding. In this approach we want to avoid any possible double encoding happening.
=> feat: don't encode url search params

src/diagonal.works/b6/ingest/compact/encoding.go
compacts no longer compatible after tag value is expression + no longer un/marsh via string changes
https://github.com/diagonalworks/diagonal-b6/commit/26ecf70f97f4c5f318508bdc2b8a331f3a261bb6
https://github.com/diagonalworks/diagonal-b6/commit/51bcb67c88e29cf1ea761dbb805fd732a2c86657
=> up backend version

src/diagonal.works/b6/cmd/b6-ingest-gdal/b6-ingest-gdal.go, src/diagonal.works/b6/cmd/b6-ingest-osm/b6-ingest-osm.go, src/diagonal.works/b6/ingest/gdal/source.go
Also add an ID strategy for ONS 2021 boundaries.
=> Support writing output from b6-ingest-gdal to cloud.

docker/Dockerfile.b6.inc, src/diagonal.works/b6/ingest/compact/build.go, src/diagonal.works/b6/ingest/compact/encoding.go, src/diagonal.works/b6/ingest/compact/read.go
Include a compact encoding version in index filenames, by replacing VERSION in filenames with the major component of the semver (eg v5).
=> Include a compact encoding version in index filenames.

frontend/src/assets/map/diagonal-map-style-rose.json, frontend/src/assets/map/diagonal-map-style.json
When a map feature includes a "colour" tag, we interpret it and use it as the fill color for the feature.
For the layers `landuse-nature`, `landuse-forest` , `landuse-urban`, `landuse-greenspaces`, `road`, `building`, we add the following case condition on the map style spec:
```
["case", ["has", "colour"],["get", "colour"], ["literal",${default color}]]
```
=> Use color tag as fill color if it exists

frontend/src/components/Outliner.tsx, frontend/src/components/adapters/LineAdapter.tsx, frontend/src/components/adapters/SubstackAdapter.tsx
This feature will enable users to copy the value or expression of an outliner to the clipboard.
We are introducing a new line action type called 'copy'. When enabled, it will display an icon button for the copy action. The copy action function will copy either the value if the line is an atomic value or the expression of the respective outliner. This copy action will be added only to the first line of an outliner, similar to the close and toggle visibility actions.
=> feat: add copy to clipboard to outliners

frontend/src/components/adapters/ShellAdapter.tsx, frontend/src/components/system/Shell.tsx, frontend/src/stores/outliners.ts, frontend/src/stores/worlds.ts
The goal is to enable the use of arrow keys to navigate the previous shell commands by adding history to the shell.
History is added to the shell and is scoped to separate histories for individual outliner shells and global history for the world shell. The command history is stored in the corresponding outliner store for outliner shells and in the world store for global shells. This history is then passed on to the `<Shell>` component as a prop.
=> Add shell history

frontend/src/components/Outliner.tsx, frontend/src/components/OutlinersLayer.tsx, frontend/src/components/adapters/SubstackAdapter.tsx, frontend/src/components/system/Line.tsx, frontend/src/lib/context/stack.tsx, frontend/src/stores/outliners.ts
Fixes issue where `evaluateNode` would not run from an outliner without a set request, as is the case with docked outliners.
If the outliner doesn't have a request set, it defaults to the current world root.
Additionally, some tweaks in the rendering outliners.
=> Fix evaluateNode from docked outliner

.editorconfig, .gitignore, src/diagonal.works/b6/cmd/b6/b6.go, src/diagonal.works/b6/elevation.go, src/diagonal.works/b6/merged.go
This adds a new `b6` command line option to add additional (mutable) worlds.
Note that this only is in effect when the world is **not** read-only. Hopefully the name is suggestive enough of that fact.
Example of usage:
```shell
nix run .#b6 -- \
-static-v2=$(nix build .#frontend --print-out-paths) \
-enable-v2-ui \
-world data/camden.index \
-add-world "/collection/diagonal.works/demo/example/0 data/some-yaml.yaml"
```
where `some-yaml.yaml` contains some information; perhaps like:
```yaml
collection:
- - centroid
- id: /path/openstreetmap.org/way/15703989
id: /collection/diagonal.works/demo/example/0
```
I.e. you just give a FeatureID and "normal string" that you would pass to `-world` and it'll load that world at that point.
Also added is an editorconfig to help enforce the coding …
=> Add additional worlds on the b6 cmdline

.editorconfig, frontend/src/assets/map/diagonal-map-style-rose.json, frontend/src/assets/map/diagonal-map-style.json, frontend/src/components/adapters/LineAdapter.tsx, frontend/src/components/system/ClickableAtom.tsx
The "colour" word in the map styles should be "b6:colour".
Also, there were a couple of JS warnings/errors that were solved by:
- ~Fixing the button-in-button to be a [button-in-div](https://github.com/diagonalworks/diagonal-b6/pull/321/files#diff-7f002c927558376676c0b0becd6e59a947fcb3d100b638b1942e4853a018caa2)~ Edit: Apparently not; with this change typescript is unhappy; so we will live with the browser being upset.
- Using "key_" instead of "key" ( https://react.dev/warnings/special-props )
- ~Installing `gl-matrix` ( https://stackoverflow.com/a/69456837 )~ Edit: No; this one we will leave as well, as it has an error during the offline pnpm build.
=> Update `colour -> b6:colour` and some other small fixes

.github/workflows/ci-nix.yaml
A small change to the CI so that it uses the right input source when checking the flake template (i.e. the one coming from the branch that triggered the build.)
Without this, if a change is made in a branch to the flake, that requires the flake template to change, the template test would fail, as it was always referring to the _main_ branch.
=> Add the flake template check back in

.github/workflows/build-latest-image.yaml, .github/workflows/publish-images.yaml
This publishes two new images:
- b6-aarch64
- b6-minimal-aarch64
built on the corresponding runner.
=> Use aarch64 runners; publish images with this info

.github/workflows/ci-nix.yaml, README.md, flake.nix, nix/docker.nix, nix/js.nix, nix/templates/python-client/flake.nix
This PR just removes the b6 js v1 UI from the build steps, as it isn't used presently.
It also formalises adding a `run-b6` entrypoint that wraps up the common arguments (and in particular the v2-ui path) so as to make working with it a bit easier.
=> Don't use V1 by default; simpler run-b6 script

src/diagonal.works/b6/version.go
Presently it's hard to indicate minor changes in the vesion as the repo uses the most minor version possible to start with. This changes it to v0.1.0, from which one can start incrementing minor versions if ones wishes!
=> Bump version so we can use minor versions

frontend/src/assets/map/diagonal-map-style.json, frontend/src/components/GeoJsonLayer.tsx, frontend/src/components/Map.tsx, frontend/src/components/system/Header.tsx, frontend/src/hooks/useHighlight.ts, src/diagonal.works/b6/renderer/renderer.go, src/diagonal.works/b6/ui/lines_test.go, src/diagonal.works/b6/ui/ui.go, src/diagonal.works/b6/version.go
- Opts to return GeoJSON if a `b6.feature` contains geometry
- Adds an amenity layer and renders it
- Draws the points in the colour specified, instead of a fixed colour
Note that the decision to return GeoJSON for features here may have some as-yet-investigated performance impacts for queries that return, say, many many features. This will need to be investigated at some point.
> [!note]
> This removed a test that was, I think, always broken when `geoJSON` was returned from a UI reponse. It seems as if the go itself can't decode this back into the type that it was originally; perhaps because of the uage of an [interface in the defining struct.](https://github.com/diagonalworks/diagonal-b6/blob/0817f61191b2e2e7cf97f2bd8a73e02913236edd/src/diagonal.works/b6/ui/ui.go#L276)
=> Highlight points and areas in GeoJSON layer; include amenities as renderable

.github/workflows/publish-to-pypi.yaml, src/diagonal.works/b6/version.go
- Bump a minor version so we can do a release
- Enable the PyPI trusted publishing workflow!
=> Enable PyPI workflow
