diagonalworks/diagonal-b6

src/diagonal.works/b6/cmd/b6/shell.go

Limit the number of items shown from collections, to protect the UI.

Limit the number of items shown from collections.

---

src/diagonal.works/b6/ingest/mutable.go

while here make point consistent with other modifiedTag*s

fix propagation error in modifyTags

---

src/diagonal.works/b6/api/shell.go
src/diagonal.works/b6/api/shell_test.go
src/diagonal.works/b6/ids.go
src/diagonal.works/b6/ingest/change_test.go
src/diagonal.works/b6/ui/ui.go
src/diagonal.works/b6/world.go

Also change the namespace abbreviation for census areas from gb to uk, to reflect the fact that the ONS is UK wide.

Added a namespace alias for codepoint.

---

python/diagonal_b6/__init__.py
python/diagonal_b6/b6_test.py
python/diagonal_b6/collection.py
python/diagonal_b6/expression.py
python/diagonal_b6/geometry.py
src/diagonal.works/b6/api/api.go
src/diagonal.works/b6/api/collections.go
src/diagonal.works/b6/api/functions/functions.go
src/diagonal.works/b6/api/functions/geometry.go
src/diagonal.works/b6/api/protos.go
src/diagonal.works/b6/api/vm.go
src/diagonal.works/b6/cmd/b6-api/b6-api.go

Add support for literal collections in Python, and also a function to compute convex hulls.

Add support for literal collections in Python.

---

src/diagonal.works/b6/api/shell.go
src/diagonal.works/b6/api/shell_test.go
src/diagonal.works/b6/cmd/b6-ingest-gb-uprn/b6-ingest-gb-uprn.go
src/diagonal.works/b6/cmd/b6/b6.go
src/diagonal.works/b6/cmd/b6/js/b6.js
src/diagonal.works/b6/go.mod
src/diagonal.works/b6/go.sum
src/diagonal.works/b6/ingest/gb/uprn/source.go
src/diagonal.works/b6/ingest/gb/uprn/source_test.go
src/diagonal.works/b6/ingest/gdal/source.go
src/diagonal.works/b6/renderer/query.go
src/diagonal.works/b6/renderer/query_test.go
src/diagonal.works/b6/renderer/renderer.go
src/diagonal.works/b6/ui/blocks.go
src/diagonal.works/b6/ui/ui.go
src/diagonal.works/b6/world.go

Also added the ability to ingest features for the cluster of UPRNs at the same rough location (by s2 cell), rather than individually.

Add a tile renderer that takes a query for features as a URL parameter.

---

python/docs/01_Search.ipynb
python/docs/env.yml

Needs a second set of eyes
Also if there is anything in particular related to search missing, please comment in this pr

connect, search, export

---

src/diagonal.works/b6/api/functions/graph.go

[reverting from collection cl ](https://github.com/diagonalworks/diagonal-b6/commit/e7750ead04989d92b0524766d43bf8080241f399#diff-d448b062b51ba13668123250145b6261804ad084ef03b422f79d329a122c052a)

make FindReachableFeaturesWithPathStates public for internal baseline 

---

src/diagonal.works/b6/grpc/service.go

(and make first message more accurate while here)

Fix typo compatiable->compatible

---

python/diagonal_b6/b6_test.py

Makes the code a bit more readable.

Refactor Python b6_test.py: extract wait_until_ready func

---

src/diagonal.works/b6/geojson/geojson.go
src/diagonal.works/b6/geometry/foster.go

Simplify switches

---

src/diagonal.works/b6/api/api.go
src/diagonal.works/b6/api/collections.go
src/diagonal.works/b6/api/functions/collections.go
src/diagonal.works/b6/api/functions/collections_test.go
src/diagonal.works/b6/api/functions/functions.go
src/diagonal.works/b6/cmd/b6/js/b6.js
src/diagonal.works/b6/cmd/b6/js/static/b6.css
src/diagonal.works/b6/ui/blocks.go

`find [#building] | map (get "#building") | histogram` on camden looks like

histogram support

---

python/diagonal_b6/b6_test.py
src/diagonal.works/b6/api/collections.go
src/diagonal.works/b6/api/functions/functions.go
src/diagonal.works/b6/api/functions/geometry.go
src/diagonal.works/b6/api/functions/geometry_test.go
src/diagonal.works/b6/cmd/b6-api/b6-api.go

Add collect-areas, which returns a single area from a collection

---

src/diagonal.works/b6/api/functions/functions.go
src/diagonal.works/b6/api/functions/materialise.go
src/diagonal.works/b6/api/materialise.go
src/diagonal.works/b6/api/materialise_test.go
src/diagonal.works/b6/cmd/b6/js/b6.js
src/diagonal.works/b6/cmd/b6/js/static/images/relation.svg
src/diagonal.works/b6/ingest/compact/read.go
src/diagonal.works/b6/ingest/yaml.go
src/diagonal.works/b6/ingest/yaml_test.go
src/diagonal.works/b6/ui/lines.go

Also support loading changes exported as YAML via the b6 --world flag.

Support materialisation of basic collections into relations

---

src/diagonal.works/b6/api/shell.go
src/diagonal.works/b6/cmd/b6/js/b6.js
src/diagonal.works/b6/cmd/b6/js/static/b6.css
src/diagonal.works/b6/ingest/compact/read.go
src/diagonal.works/b6/ui/lines.go

Also make the loading of world files consistent by sorting filenames, and outlines around map dots.

Don't show layers for closed items in the dock on the map.

---

src/diagonal.works/b6/cmd/b6/js/b6.js
src/diagonal.works/b6/cmd/b6/js/static/b6.css
src/diagonal.works/b6/cmd/b6/js/static/images/dot-cyan.svg
src/diagonal.works/b6/cmd/b6/js/static/images/dot-stone.svg
src/diagonal.works/b6/cmd/b6/js/static/images/dot-violet.svg
src/diagonal.works/b6/cmd/b6/js/static/images/dot-yellow.svg

Also add more analysis colours.

Remove the on-map UI for docked items while they're closed.

---

src/diagonal.works/b6/cmd/b6/js/b6.js

Also rename RenderedResponse to Stack.

Render the results from a stack in the same stack.

---

src/diagonal.works/b6/api/functions/graph.go
src/diagonal.works/b6/api/functions/graph_test.go
src/diagonal.works/b6/cmd/b6/js/b6.js
src/diagonal.works/b6/cmd/b6/js/static/b6.css

Also cache style objects to improve rendering speed when there's a large number of points.

Add a zero bucket to accessibility histograms.

---

src/diagonal.works/b6/expression.go
src/diagonal.works/b6/geojson/geojson.go
src/diagonal.works/b6/geometry/multipolygon.go
src/diagonal.works/b6/search.go
src/diagonal.works/b6/spatial.go

Also add Equal() to Expression and Query

Basic support for rendering expression features

---

src/diagonal.works/b6/cmd/b6/js/b6.js

Also close all docked stacks when creating a new stack (as it may add its own bucket colours to the map).

Remove bucked colours when docked stacks are collapsed.

---

src/diagonal.works/b6/cmd/b6/js/b6.js
src/diagonal.works/b6/cmd/b6/js/static/b6.css

Also support showing a single bucket.

Add a message when copying.

---

docker/Dockerfile.b6.inc
frontend/Makefile
frontend/package.json
src/diagonal.works/b6/cmd/b6/b6.go
src/diagonal.works/b6/ui/ui.go

Renames the output directory of storybook from storybook-static to dist-storybook for consistency.

Optionally expose storybook from the b6 binary.

---

python/diagonal_b6/features.py
python/diagonal_b6/generate_api.py
src/diagonal.works/b6/api/functions/docs.go
src/diagonal.works/b6/api/functions/features.go
src/diagonal.works/b6/api/functions/functions.go
src/diagonal.works/b6/cmd/b6-api/b6-api.go
src/diagonal.works/b6/ingest/yaml.go

In passing, set the sorted flag on collections loaded from YAML that are sorted, to speed rendering of serialised histograms.

Support using collection features as collections in Python.

---

.gitignore
frontend/.gitignore
src/diagonal.works/b6/world.go

Delete commented-out code

---

python/diagonal_b6/b6_test.py
src/diagonal.works/b6/api/functions/change.go
src/diagonal.works/b6/api/functions/docs.go
src/diagonal.works/b6/api/functions/functions.go
src/diagonal.works/b6/api/functions/graph.go
src/diagonal.works/b6/renderer/icons.go
src/diagonal.works/b6/ui/ui.go

Also reduce the set of features used to form a network in connect-to-network, and correct icon rules.

Added add-point

---

src/diagonal.works/b6/api/functions/docs.go
src/diagonal.works/b6/api/functions/functions.go
src/diagonal.works/b6/api/functions/graph.go
src/diagonal.works/b6/api/functions/sightline.go
src/diagonal.works/b6/api/functions/sightline_test.go
src/diagonal.works/b6/ui/ui.go
src/diagonal.works/b6/world.go

Added a entrance-approach, which returns a point close to the entrance of an area, or an invalid point if the area isn't connected.

Added entrance-approach.

---

src/diagonal.works/b6/ingest/compact/encoding.go

use zigzag for lat/value type and 32/instead of 64 bytes for lng encoding
while here return correct max size for latlng encoding

decrease latlng encoding size

---

src/diagonal.works/b6/api/evaluator.go

Factors out the code for applying changes to worlds into a new Evaluator struct.

Add a handler to evaluate expressions as JSON.

---

python/diagonal_b6/expression.py
src/diagonal.works/b6/api/functions/change.go
src/diagonal.works/b6/ui/histogram.go

Also empty the a world modified by add-world-with-change before applying the change.

Support adding labels to histogram features.

---

python/diagonal_b6/expression.py
python/diagonal_b6/features.py
src/diagonal.works/b6/api/functions/collections.go
src/diagonal.works/b6/api/functions/collections_test.go
src/diagonal.works/b6/api/functions/docs.go
src/diagonal.works/b6/api/functions/functions.go
src/diagonal.works/b6/protos.go

Added join-missing, which fills in missing keys from one collection from another.

Added join-missing.

---

frontend/src/atoms/location.ts
frontend/src/atoms/startup.ts
frontend/src/components/ScenarioMap.tsx
frontend/src/lib/b6.ts
frontend/src/lib/context/app.tsx
frontend/src/lib/context/outliner.tsx
frontend/src/lib/context/scenario.tsx

Don't send the ll= URL parameter to the startup request, as it'll override the center defined in the world.

Use the base URL for basemap tiles, and set the center on startup.

---

frontend/src/components/system/Histogram.tsx

Little fixes regarding the labels on the histogram:

fix: histogram labels

---

frontend/src/components/ScenarioMap.tsx

Add antialias to the map.
Note: there might be an impact on performance, I didn't see anything drastic on my end - let's test it out.

feat: add antialiasing to map

---

src/diagonal.works/b6/api/functions/features.go
src/diagonal.works/b6/api/functions/functions.go
src/diagonal.works/b6/api/functions/sightline.go
src/diagonal.works/b6/graph/connectivity.go
src/diagonal.works/b6/graph/graph.go
src/diagonal.works/b6/graph/graph_test.go
src/diagonal.works/b6/ingest/basic.go
src/diagonal.works/b6/ingest/compact/world.go
src/diagonal.works/b6/ingest/mutable.go
src/diagonal.works/b6/ingest/testing.go
src/diagonal.works/b6/renderer/histogram.go
src/diagonal.works/b6/renderer/query.go
src/diagonal.works/b6/renderer/renderer.go
src/diagonal.works/b6/ui/lines.go
src/diagonal.works/b6/world.go

search world for features that are references / use wrapped physical feature instead

remove nested physical feature interface

---

src/diagonal.works/b6/protos.go
src/diagonal.works/b6/ui/ui.go

Also correctly serve the v1 UX index page.

Correctly marshal the invalid feature type.

---

src/diagonal.works/b6/api/functions/graph.go
src/diagonal.works/b6/expression.go
src/diagonal.works/b6/graph/connectivity.go
src/diagonal.works/b6/ingest/change_test.go
src/diagonal.works/b6/ingest/compact/encoding.go
src/diagonal.works/b6/ingest/compact/overlay_test.go
src/diagonal.works/b6/ingest/features.go
src/diagonal.works/b6/ingest/mutable_test.go
src/diagonal.works/b6/ingest/yaml_test.go
src/diagonal.works/b6/search.go
src/diagonal.works/b6/world.go

once we remove literals, we can consolidate FeatureIDExpression and FeatureID

use FeatureIDExpression for tag value

---

src/diagonal.works/b6/api/shell.go
src/diagonal.works/b6/api/shell_test.go
src/diagonal.works/b6/cmd/b6/js/b6.js
src/diagonal.works/b6/ingest/colouring.go
src/diagonal.works/b6/renderer/collection.go
src/diagonal.works/b6/renderer/collection_test.go
src/diagonal.works/b6/renderer/histogram.go
src/diagonal.works/b6/renderer/renderer.go
src/diagonal.works/b6/renderer/renderer_test.go
src/diagonal.works/b6/tiles.go
src/diagonal.works/b6/ui/lines.go
src/diagonal.works/b6/ui/ui.go
src/diagonal.works/b6/world.go

In passing, correct a bug when unparsing expressions with a call without arguments.

Render collections that contain features as a tile layer.

---

src/diagonal.works/b6/cmd/b6/js/b6.js

Also render both features from keys and values via the collection layer, rather than just the values.

Fix clicks on collection keys and values in the old UI.

---

frontend/src/components/adapters/LineAdapter.tsx
frontend/src/components/system/ClickableAtom.tsx

Make the atoms in left-right lines clickable in the v2 UI.

---

.github/workflows/build-latest-image.yaml
.github/workflows/ci-nix.yaml
.github/workflows/ci-plain.yaml
.github/workflows/publish-images.yaml
README.md
docker/Dockerfile.b6-build.inc
flake.lock
flake.nix
nix-templates/python-client/flake.nix
nix/python-client/flake.nix

- Fix the cloudbuild yaml to explicitly instally pnpm; as this used to be in the Makefile.
- Fix the docker-publishing matrix configuration; forgot the term "matrix!"

Fix cloudbuild and matrix config

---

src/diagonal.works/b6/cmd/b6/b6.go

- Throw an error if the featureId you provide is invalid.
- Run `ReadWorld` for the added worlds after the base one has finished.

Minor fix to load only after base-world

---

docs/docs/b6-api-documentation.md
scripts/api-docs-to-docusaurus.py

A small addition to the docs: List the functions grouped by return type. This can be convenient to know if you're searching for some specific functions on specific types!

List functions by return-type

---

flake.nix

Not trying cross-compilation anymore, so no need for this particular structure.

Minor nix cleanup

---

src/diagonal.works/b6/ui/ui.go

This allows you to specify a point as your centroid, instead of requiring a point feature.
I.e. you can now do:
```python
add_root = b6.add_collection(root, {}, b6.collection(
b6.pair("centroid", b6.ll(55.9480999, -3.2000552)),
))
...
```
to define the centroid of the `root` world that is being added.

Allow the centroid to be specified via a simple point

---

frontend/src/assets/map/diagonal-map-style-rose.json
frontend/src/assets/map/diagonal-map-style.json

Helps to distinguish between land and water

Thicker coastline border

---

nix/templates/python-client/flake.lock

We can update this as we please; but this ensures we will always be buildable as a template.

Add a flake.lock to the nix template

---

src/diagonal.works/b6/ui/lines_test.go

This restores the test that was removed in #357 .
The trick was to partially-decode the response and just ignore the part the test doesn't check.
There may well be a much more idiomatic way to do this ( cc @andreweland ) but in lieu of that, this works fine.

Re-instate test with some json-decoding hacks

---

.github/workflows/ci-nix.yaml
.github/workflows/publish-docker-images.yaml
.github/workflows/publish-to-pypi.yaml
flake.nix
nix/python.nix

This introduces a nix derivation to build a Python wheel:
```shell
nix build .#wheel
```
This also adds steps to publish the latest version to PyPI when a release is made (i.e. a tag is pushed).
Todo:

Build Python wheel
